name: test

on:
  workflow_dispatch:

jobs:
  testtest:
    runs-on: codebuild-test-github-actions-self-hosted-runner-codebuild-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: apt update
        uses: sudo apt update

      - name: install python
        uses: sudo apt install -y python3 python3-pip

      - name: install requirements.txt
        run: pip install -r requirements.txt

      - name: run main.py
        run: python main.py