name: test

on:
  workflow_dispatch:

jobs:
  testtest:
    runs-on: codebuild-test-github-actions-self-hosted-runner-codebuild-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "latest"

      - name: install requirements.txt
        run: pip install -r requirements.txt

      - name: run main.py
        run: python main.py